-- Lifeline — Tier 1 (Supabase / Postgres). Espelha o ledger local, multi-tenant via RLS.
-- Cole no SQL Editor do seu projeto (Dashboard → SQL Editor → New query → Run).
-- NÃO precisa compartilhar nenhuma key para rodar isto — é no seu dashboard.
--
-- Append-only POR CONSTRUÇÃO: só SELECT e INSERT têm policy → UPDATE/DELETE são negados
-- pela RLS. Isso impõe a Lei #2 (append-only) e a Lei #1 (âncora) no próprio banco.

create table if not exists lifeline_entries (
  seq        bigint generated by default as identity,   -- ordem causal (inserção), por usuário/line
  owner      uuid not null default auth.uid(),           -- tenant: dono da entrada (multi-tenant)
  line       text not null default 'ledger',             -- qual line (código OU conversa)
  id         text not null,                              -- id content-addressed (sha256 do conteúdo+pais)
  ts         timestamptz not null default now(),         -- metadado (fora do hash)
  kind       text not null,
  summary    text not null,
  body       text not null default '',
  parents    jsonb not null default '[]'::jsonb,
  dedup_key  text,
  payload    jsonb not null,                             -- o Entry completo (Entry.model_dump_json)
  primary key (owner, line, id)                          -- dedup por conteúdo, isolado por tenant/line
);

create index if not exists idx_lifeline_owner_line_seq
  on lifeline_entries (owner, line, seq);

create unique index if not exists idx_lifeline_dedup
  on lifeline_entries (owner, line, dedup_key)
  where dedup_key is not null;

alter table lifeline_entries enable row level security;

-- Cada usuário só LÊ e só INSERE as próprias entradas. (Sem policy de UPDATE/DELETE
-- → a RLS nega por padrão → append-only no banco.)
drop policy if exists "lifeline_select_own" on lifeline_entries;
create policy "lifeline_select_own" on lifeline_entries
  for select using (owner = auth.uid());

drop policy if exists "lifeline_insert_own" on lifeline_entries;
create policy "lifeline_insert_own" on lifeline_entries
  for insert with check (owner = auth.uid());

-- (Futuro M4 / hub: policies de compartilhamento por line — uma tabela de membros por line
-- e uma policy que libera SELECT a membros. Fora do escopo do Tier 1.)
