import hashlib
import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Literal

from pydantic import BaseModel, Field, model_validator

from .types import EventID, WorkflowID, AgentID, TaskID, ExecutionID, State, ContextReferences

def utcnow() -> datetime:
    return datetime.now(timezone.utc)

# The unified enum for runtime states
WorkflowState = Literal[
    "PENDING", "READY", "RUNNING", "WAITING", "RETRYING", 
    "COMPLETED", "FAILED", "CANCELLED", "TIMEOUT", "ROLLEDBACK"
]

# Failure Domains for recovery routing
FailureDomain = Literal["COGNITIVE", "INFRASTRUCTURE", "WORKFLOW", "TOOL", "SECURITY"]

class EventBase(BaseModel):
    """
    Base model for all events. 
    Acts as the fundamental primitive of the causal cognitive ledger.
    Graph-native by relying on `parent_event_ids` to permit operational branching, forks, and joins.
    """
    event_id: EventID = Field(default="")
    
    # Causal Graph linking (replaces linear previous_event_hash)
    parent_event_ids: List[EventID] = Field(default_factory=list)
    
    # Causality and physical ordering metrics
    logical_clock: int = Field(default=0, description="Lamport-style scalar clock for distributed causality verification")
    timestamp: datetime = Field(default_factory=utcnow)
    
    # Robust version governance
    schema_version: str = "1.0.0"
    protocol_version: str = "1.0.0"
    engine_version: str = "1.0.0"
    
    # Contextual scope IDs
    kernel_id: Optional[str] = None
    agent_id: Optional[AgentID] = None
    workflow_id: Optional[WorkflowID] = None
    task_id: Optional[TaskID] = None
    execution_id: Optional[ExecutionID] = None
    workflow_node_id: Optional[str] = None

    # Snapshot reference (for fast recovery checkpoint associations)
    associated_snapshot_id: Optional[str] = None
    
    # Idempotency & Deduplication Key
    deduplication_key: Optional[str] = None

    # Operational lineage payload
    state_before: Optional[State] = None
    state_after: Optional[State] = None
    
    # Cognitive / Reasoning payload
    reasoning_summary: Optional[str] = None
    tools_used: Optional[List[Dict[str, Any]]] = None
    execution_metadata: Optional[Dict[str, Any]] = None
    context_references: Optional[ContextReferences] = None

    def seal(self, parent_hashes: List[str], logical_clock: int) -> str:
        """
        Criptograficamente vincula o evento aos seus predecessores e relógio lógico.
        O event_id emerge deterministicamente da colagem estrutural do DAG.
        """
        self.parent_event_ids = parent_hashes
        self.logical_clock = logical_clock
        
        event_dict = self.model_dump(exclude={"event_id"}, mode="json")
        json_str = json.dumps(event_dict, sort_keys=True, separators=(',', ':'))
        
        self.event_id = hashlib.sha256(json_str.encode('utf-8')).hexdigest()
        return self.event_id

    @model_validator(mode="after")
    def initial_compute(self) -> "EventBase":
        if not self.event_id:
            event_dict = self.model_dump(exclude={"event_id"}, mode="json")
            json_str = json.dumps(event_dict, sort_keys=True, separators=(',', ':'))
            self.event_id = hashlib.sha256(json_str.encode('utf-8')).hexdigest()
        return self

class SystemEvent(EventBase):
    """Events generated by the kernel or hardware infrastructure."""
    event_type: Literal["system"] = "system"
    action: str

class WorkflowEvent(EventBase):
    """Legacy or generic workflow action events."""
    event_type: Literal["workflow"] = "workflow"
    status: str

class WorkflowStateTransitionEvent(EventBase):
    """
    Formally registers formal operational state transitions.
    Crucial for state machine verification, rollbacks, and audits.
    """
    event_type: Literal["state_transition"] = "state_transition"
    from_state: Optional[WorkflowState] = None
    to_state: WorkflowState
    trigger: str
    transition_metadata: Optional[Dict[str, Any]] = None

class AgentEvent(EventBase):
    """Represents an explicit agent cognitive action."""
    event_type: Literal["agent"] = "agent"
    action: str  # e.g., "think", "act", "observe", "plan"
    prompt: Optional[str] = None
    completion: Optional[str] = None

class ToolExecutionEvent(EventBase):
    """
    Tracks tool lifecycle, duration, inputs, outputs, side-effects, and errors.
    Enables physical and logical tool replay.
    """
    event_type: Literal["tool_execution"] = "tool_execution"
    tool_name: str
    tool_args: Dict[str, Any]
    tool_result: Optional[Any] = None
    error: Optional[str] = None
    side_effects: Optional[Dict[str, Any]] = None  # Track network calls, stdout, file diffs
    execution_duration: Optional[float] = None

class FailureEvent(EventBase):
    """
    Registers an operational failure categorizing its root Domain.
    Essential for auto-healing routing and specialized Context reconstruction.
    """
    event_type: Literal["failure"] = "failure"
    failure_domain: FailureDomain
    error_message: str
    stack_trace: Optional[str] = None
    recovered: bool = False
    contextual_remedy: Optional[str] = None

class BranchMergeEvent(EventBase):
    """
    Formalizes the union of parallel execution branches.
    Captures the logic path converging, and lists the merged states for reconciliation.
    """
    event_type: Literal["branch_merge"] = "branch_merge"
    converged_from_branches: List[str] = Field(description="List of leaf EventIDs converging")
    reconciliation_strategy: str
    merged_state_summary: Optional[Dict[str, Any]] = None


def parse_event_from_json(payload_json: str) -> EventBase:
    """Centralized industrial deserialization factory for all ledger events."""
    payload = json.loads(payload_json)
    event_type = payload.get("event_type", "base")
    
    if event_type == "system":
        return SystemEvent(**payload)
    elif event_type == "workflow":
        return WorkflowEvent(**payload)
    elif event_type == "state_transition":
        return WorkflowStateTransitionEvent(**payload)
    elif event_type == "agent":
        return AgentEvent(**payload)
    elif event_type == "tool_execution":
        return ToolExecutionEvent(**payload)
    elif event_type == "failure":
        return FailureEvent(**payload)
    elif event_type == "branch_merge":
        return BranchMergeEvent(**payload)
    else:
        return EventBase(**payload)

